"""Aggregate EmerNeRF eval-time JSON outputs for one scene and update the
SplatAD-vs-NeuRAD comparison table at ~/ETH/FoggyField/experiments/0.2_neurad_repro.md.

Usage:
    python emernerf_collect_metrics.py <log_dir> <scene>

Strategy:
  1. Read the latest images_test_*.json (test-set eval) from <log_dir>/metrics/.
  2. Write a per-scene metrics.json next to it for downstream consumers.
  3. Append/update a section §10 "EmerNeRF RGB-only baseline" in the markdown,
     showing scene-by-scene numbers for whatever scenes have completed so far.
"""
from __future__ import annotations

import json
import re
import sys
from datetime import datetime
from pathlib import Path

DOC_PATH = Path("/networkhome/WMGDS/wang3_y/ETH/FoggyField/experiments/0.2_neurad_repro.md")
COMP_OUTPUTS_ROOT = Path("/networkhome/WMGDS/wang3_y/ETH/Code/SplatAD/outputs")


def latest_metrics_file(log_dir: Path, kind: str) -> Path | None:
    candidates = sorted(log_dir.glob(f"metrics/images_{kind}_*.json"))
    return candidates[-1] if candidates else None


def collect_scene(log_dir: Path, scene: str) -> dict:
    out = {"scene": scene, "log_dir": str(log_dir), "extracted_at": datetime.now().isoformat()}
    for kind, prefix in [("test", "pixel_metrics/test/"), ("full", "pixel_metrics/full/")]:
        f = latest_metrics_file(log_dir, kind)
        if not f:
            out[f"{kind}_metrics_file"] = None
            continue
        with open(f) as fh:
            d = json.load(fh)
        clean = {}
        for k, v in d.items():
            if k.startswith(prefix):
                clean[k[len(prefix):]] = v
        out[f"{kind}_metrics_file"] = str(f)
        out[f"{kind}_metrics"] = clean
    return out


def all_scene_metrics() -> dict:
    """Walk outputs/emernerf_*_split05/ and grab whichever scenes have written metrics."""
    scenes = {}
    for d in sorted(COMP_OUTPUTS_ROOT.glob("emernerf_*_split05")):
        m = re.match(r"emernerf_(\d+)_split05", d.name)
        if not m:
            continue
        scene = m.group(1)
        # find the scene_<id>/<ts>/ run dir
        run_dirs = list(d.glob(f"foggyfields_emernerf/scene_{scene}*"))
        if not run_dirs:
            run_dirs = list(d.glob(f"*/scene_{scene}*"))
        if not run_dirs:
            continue
        log_dir = sorted(run_dirs)[-1]
        sc = collect_scene(log_dir, scene)
        if "test_metrics" in sc:
            scenes[scene] = sc
    return scenes


def format_md_table(scenes: dict) -> str:
    """Render the EmerNeRF rows + comparison context."""
    lines = ["",
             "## 10. EmerNeRF (RGB-only) baseline",
             "",
             "**Method:** EmerNeRF static config (`configs/default_config.yaml` overrides via `configs/pandaset.yaml`), 30k iter, num_cams=5 (drop back camera), PandaSet → EmerNeRF dataparser at `datasets/pandaset.py`, test_image_stride=2 (matches train_split_fraction=0.5).",
             "",
             "**Note:** Static-scene config — no dynamic decomposition (dynamic actors may render as ghosting). RGB-only training; no LiDAR supervision (which is one of EmerNeRF's options but not the default).",
             "",
             "### RGB metrics (test split, full val set)",
             "",
             "| Scene | **PSNR** ↑ | **SSIM** ↑ | **LPIPS** ↓ | extracted from |",
             "|---|---|---|---|---|"]
    for scene_id in sorted(scenes.keys()):
        sc = scenes[scene_id]
        m = sc.get("test_metrics", {}) or sc.get("full_metrics", {})
        psnr = m.get("psnr", float("nan"))
        ssim = m.get("ssim", float("nan"))
        lpips = m.get("lpips", float("nan"))
        src = Path(sc.get("test_metrics_file") or sc.get("full_metrics_file") or "").name
        lines.append(f"| {scene_id} | {psnr:.2f} | {ssim:.3f} | {lpips:.3f} | `{src}` |")
    lines.append("")
    lines.append("### Quick sanity vs the 4-method table in §3")
    lines.append("")
    lines.append("EmerNeRF static is a NeRF-style purely-radiance model with no dynamic actor handling and no LiDAR supervision, so we *expect* it to under-perform NeuRAD-paper (which also uses LiDAR depth as supervision and has dynamic-actor decomposition) by a meaningful margin. If the gap is < 1 dB the dataparser is suspect; if it lags by 2–4 dB that's consistent with EmerNeRF's published numbers vs NeuRAD on AD scenes.")
    lines.append("")
    lines.append("### Visualisations")
    for scene_id in sorted(scenes.keys()):
        log_dir = Path(scenes[scene_id]["log_dir"])
        vids = list((log_dir / "videos").glob("*.mp4"))
        if vids:
            lines.append(f"- scene **{scene_id}** videos: `{log_dir / 'videos'}` (auto-generated by EmerNeRF after eval; `rgbs_*.mp4` is the rendered RGB video, `gt_rgbs_*.mp4` is GT)")
    lines.append("")
    return "\n".join(lines)


def update_markdown(scenes: dict) -> None:
    if not scenes:
        print("[collect] no scenes have metrics yet; skipping markdown update")
        return
    body = format_md_table(scenes)
    text = DOC_PATH.read_text() if DOC_PATH.exists() else ""
    pattern = re.compile(r"\n## 10\. EmerNeRF \(RGB-only\) baseline.*?(?=\n## |\Z)", re.DOTALL)
    if pattern.search(text):
        text = pattern.sub(body, text)
    else:
        text = text.rstrip() + "\n" + body + "\n"
    DOC_PATH.write_text(text)
    print(f"[collect] updated {DOC_PATH} with {len(scenes)} EmerNeRF scene rows")


def main():
    if len(sys.argv) < 3:
        print("Usage: emernerf_collect_metrics.py <log_dir> <scene>")
        sys.exit(2)
    log_dir = Path(sys.argv[1])
    scene = sys.argv[2]
    sc = collect_scene(log_dir, scene)
    # Write per-scene metrics.json next to the log dir (above the timestamp run dir).
    out = COMP_OUTPUTS_ROOT / f"emernerf_{scene}_split05" / "metrics.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w") as f:
        json.dump(sc, f, indent=2)
    print(f"[collect] wrote {out}")

    scenes = all_scene_metrics()
    update_markdown(scenes)


if __name__ == "__main__":
    main()
